// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"KMS_Minimap","status":true,"description":"[v0.2.0] Display minimap.","parameters":{"Map rect":"524, 32, 260, 200","Grid size":"10","Blink time":"180","Foreground color":"rgba(224, 224, 240, 0.6)","Background color":"rgba(0, 0, 160, 0.6)","Mask style":"0","Mask radius":"48"}}
];
